### ISSUE TITLE
Move trilinos-for-albany to E3SM-Project/Trilinos?

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#19]
@ikalash, what do you think about moving our `trilinos-for-albany` package to point to `E3SM-Project/Trilinos` in the `spack/develop` branch?  This is where we can make tags for Compass, so it would be helpful to us here but it might cause you trouble.  I don't know how closely the `develop` branch on the E3SM-Project fork tracks the `develop` branch on the main repo, or what the procedure is for updating it.

@bartgol, same question to you, what do you think?  What could the issues be?

**Comment by bartgol** [comment]
I guess I answered this in #20. Bottom line: we can add some automation that keeps e3sm-project fork up-to-date with main trilinos, if that's necessary.

**Comment by ikalash** [comment]
Sorry for my non-responsiveness.  I had to work on something else that's time critical this morning, and am just now getting caught up on these threads.  

Just to make sure I understood: are you suggesting to use Trilinos from this repo: https://github.com/E3SM-Project/trilinos instead of from https://github.com/sandialabs/Trilinos?  The only issue with this is if changes are made to Albany that go hand-in-hand with Trilinos VOTD in the main Trilinos repo.  Then this will break the spack Albany build.  I have no idea about the syncing process b/w the E3SM-Project and sandialabs Trilinos or who is responsible for that...  I actually didn't even know until just now that there was an E3SM Trilinos fork!

I was going to offer to do this but I think you created a PR.  I will take a look.

**Comment by bartgol** [comment]
I added a github action to our trilinos fork, which updates our develop branch nightly. I could increase the frequency, if that's needed, but I think in most cases one update/day will be enough (I can't make the action trigger whenever trilinos/develop is updated, since the action cannot be triggered by an event on another repo).

See action log here:

https://github.com/E3SM-Project/Trilinos/actions/runs/6357080101

After tonight, I will be able to verify that the periodicity of the action works as expected.

Note: the action can be triggered manually from [here](https://github.com/E3SM-Project/Trilinos/actions/workflows/sync_develop_with_upstream.yml) (see "Run workflow" on the top right), so if an update is _really_ necessary during the day, anyone with write privileges can manually run the action.

**Comment by bartgol** [comment]
@xylar Given the above, I think it's safe to switch to the e3sm-project/trilinos fork.

**Comment by xylar** [comment]
I can confirm that there is a solution for getting `compass-*` tags from https://github.com/E3SM-Project/Trilinos and still getting the rest from https://github.com/sandialabs/Trilinos in #22, so no need to move to the E3SM-Project url for all builds.
